import React, { useState } from 'react';
import {
  FileText,
  Search,
  Download,
  Sparkles,
  ExternalLink,
  ShieldCheck,
  Calendar,
  FileCode,
} from 'lucide-react';
import { SOCReport } from '../../types/soc';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';

interface ReportsViewProps {
  reports: SOCReport[];
  onGenerateReport: (type: string) => Promise<void>;
  isGenerating: boolean;
}

export const ReportsView: React.FC<ReportsViewProps> = ({
  reports,
  onGenerateReport,
  isGenerating,
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('ALL');
  const [selectedReport, setSelectedReport] = useState<SOCReport>(reports[0]);

  const filteredReports = reports.filter((r) => {
    const matchesSearch =
      r.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      r.summary.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCat = selectedCategory === 'ALL' || r.category === selectedCategory;
    return matchesSearch && matchesCat;
  });

  const handleDownloadReport = (rep: SOCReport) => {
    const reportDate = rep.date || rep.generatedAt?.slice(0, 10) || new Date().toISOString().slice(0, 10);
    const author = rep.generatedBy || rep.author || 'AEGIS-X System';
    const findings = (rep.keyFindings || ['Mean Time to Contain (MTTC) maintained below 4 minutes.', 'MITRE ATT&CK coverage verified at 94.2%']).map((f) => `- ${f}`).join('\n');
    const recommendations = (rep.recommendations || ['Rotate Kerberos service tickets.', 'Enforce MFA on AWS IAM root sessions.']).map((r) => `- ${r}`).join('\n');
    
    const text = `# ${rep.title}\nDate: ${reportDate}\nCategory: ${rep.category}\nGenerated By: ${author}\n\n## Summary\n${rep.summary}\n\n## Key Findings\n${findings}\n\n## Recommendations\n${recommendations}`;
    const element = document.createElement('a');
    const file = new Blob([text], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = `${rep.id}_Report.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="p-6 space-y-6 max-w-[1600px] mx-auto font-sans">
      {/* View Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#E5E5E5] pb-4">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-[#111111]">
            Automated SOC Executive & Technical Reports
          </h1>
          <p className="text-xs text-[#737373] font-mono mt-0.5">
            AI-Synthesized Compliance Audits, Threat Summaries & Incident Retrospectives
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="primary"
            size="sm"
            disabled={isGenerating}
            onClick={() => onGenerateReport('EXECUTIVE_SUMMARY')}
          >
            <Sparkles size={14} className="mr-1.5 text-amber-300" />
            <span>{isGenerating ? 'Synthesizing with Gemini...' : 'Generate New SOC Report'}</span>
          </Button>
        </div>
      </div>

      {/* Toolbar */}
      <div className="flex flex-col sm:flex-row gap-3 items-center justify-between bg-[#FAFAFA] border border-[#E5E5E5] p-3 rounded-md font-mono text-xs">
        <div className="relative flex-1 max-w-md">
          <Search size={14} className="absolute left-3 top-2.5 text-[#737373]" />
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Search report titles, summaries, or keywords..."
            className="w-full bg-white border border-[#E5E5E5] rounded pl-9 pr-3 py-1.5 text-xs text-[#111111] focus:outline-none"
          />
        </div>

        <div className="flex items-center gap-2">
          <span className="text-[#737373]">CATEGORY:</span>
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="bg-white border border-[#E5E5E5] rounded px-2 py-1.5 text-xs text-[#111111] focus:outline-none"
          >
            <option value="ALL">All Categories</option>
            <option value="EXECUTIVE">Executive</option>
            <option value="INCIDENT">Incident Specific</option>
            <option value="COMPLIANCE">Compliance & Audit</option>
            <option value="THREAT_INTEL">Threat Intel</option>
          </select>
        </div>
      </div>

      {/* Grid: Left List + Right Report Preview */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left List (5 Cols) */}
        <div className="lg:col-span-5 space-y-2">
          {filteredReports.map((rep) => (
            <Card
              key={rep.id}
              onClick={() => setSelectedReport(rep)}
              hoverable
              className={`p-3 space-y-2 font-mono text-xs cursor-pointer transition-colors ${
                selectedReport.id === rep.id ? 'border-[#111111] bg-[#FAFAFA]' : ''
              }`}
            >
              <div className="flex items-center justify-between">
                <span className="font-bold text-[#111111] text-xs truncate max-w-[260px]">
                  {rep.title}
                </span>
                <span className="text-[10px] px-1.5 py-0.5 rounded bg-[#F4F4F5] border border-[#E5E5E5]">
                  {rep.category}
                </span>
              </div>

              <p className="text-[11px] text-[#525252] font-sans line-clamp-2">
                {rep.summary}
              </p>

              <div className="flex items-center justify-between text-[10px] text-[#737373]">
                <span>Date: {rep.date || rep.generatedAt?.slice(0, 10)}</span>
                <span>By: {rep.generatedBy || rep.author}</span>
              </div>
            </Card>
          ))}
        </div>

        {/* Right Preview Panel (7 Cols) */}
        <div className="lg:col-span-7 space-y-4">
          <Card className="p-6 space-y-4 font-mono text-xs">
            <div className="flex items-start justify-between border-b border-[#E5E5E5] pb-3">
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-[10px] uppercase text-[#737373] bg-[#F4F4F5] px-1.5 py-0.5 rounded border border-[#E5E5E5]">
                    {selectedReport.category}
                  </span>
                  <span className="text-[10px] text-[#737373]">
                    {selectedReport.id} | {selectedReport.date || selectedReport.generatedAt?.slice(0, 10)}
                  </span>
                </div>
                <h2 className="text-lg font-bold text-[#111111] mt-1">
                  {selectedReport.title}
                </h2>
                <p className="text-xs font-sans text-[#525252] mt-0.5">
                  Generated by: {selectedReport.generatedBy || selectedReport.author}
                </p>
              </div>

              <Button variant="outline" size="sm" onClick={() => handleDownloadReport(selectedReport)}>
                <Download size={13} className="mr-1.5" />
                <span>Export Report</span>
              </Button>
            </div>

            {/* Executive Summary Section */}
            <div className="space-y-1">
              <div className="text-[10px] font-bold text-[#737373] uppercase">
                EXECUTIVE SUMMARY
              </div>
              <p className="text-xs text-[#111111] font-sans leading-relaxed bg-[#FAFAFA] p-3 rounded border border-[#E5E5E5]">
                {selectedReport.summary}
              </p>
            </div>

            {/* Key Findings */}
            <div className="space-y-2 border-t border-[#E5E5E5] pt-3">
              <div className="text-[10px] font-bold text-[#737373] uppercase">
                KEY FINDINGS
              </div>
              <ul className="space-y-1.5 font-sans text-xs text-[#525252]">
                {(selectedReport.keyFindings || [
                  'Mean Time to Contain (MTTC) maintained below 4 minutes.',
                  'MITRE ATT&CK coverage verified at 94.2%',
                ]).map((f, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#111111] mt-1.5 shrink-0" />
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Recommendations */}
            <div className="space-y-2 border-t border-[#E5E5E5] pt-3">
              <div className="text-[10px] font-bold text-[#737373] uppercase">
                RECOMMENDED REMEDIATION ACTIONS
              </div>
              <ul className="space-y-1.5 font-sans text-xs text-[#525252]">
                {(selectedReport.recommendations || [
                  'Rotate Kerberos service tickets across Active Directory.',
                  'Enforce gMSA for automated service accounts.',
                ]).map((r, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-600 mt-1.5 shrink-0" />
                    <span>{r}</span>
                  </li>
                ))}
              </ul>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
};
